-intstyle "ise" -incremental -lib "secureip" -o "/home/ise/projekty_ucisw/projekt_ucisw_v1/testbench_isim_beh.exe" -prj "/home/ise/projekty_ucisw/projekt_ucisw_v1/testbench_beh.prj" "work.testbench" 
